// Component: <!-- Header -->
class Header extends React.Component {
  render() {
    return /*#__PURE__*/React.createElement("header", null, /*#__PURE__*/React.createElement("div", {
      className: "logo"
    }, /*#__PURE__*/React.createElement("div", {
      className: "logo-icon"
    }, "\uD83C\uDF87"), /*#__PURE__*/React.createElement("span", {
      className: "logo-text"
    }, "Hana", /*#__PURE__*/React.createElement("span", null, "bi-3"))));
  }
}

// Component: <!-- Footer -->
class Footer extends React.Component {
  render() {
    return /*#__PURE__*/React.createElement("footer", null, /*#__PURE__*/React.createElement("div", {
      className: "footer-content"
    }, /*#__PURE__*/React.createElement("p", null, "@ All images on this website are generated by Gemini AI."), /*#__PURE__*/React.createElement("p", null, "@ v3.0.0")));
  }
}

// Component: <!-- Events Card Section -->
class EventsCard extends React.Component {
  render() {
    const {
      event
    } = this.props;
    return /*#__PURE__*/React.createElement("div", {
      className: "event-card"
    }, /*#__PURE__*/React.createElement("div", {
      className: "event-image"
    }, /*#__PURE__*/React.createElement("img", {
      src: event.img,
      alt: event.name,
      title: event.imgTitle
    }), /*#__PURE__*/React.createElement("div", {
      className: "event-date-badge"
    }, /*#__PURE__*/React.createElement("div", {
      className: "day"
    }, event.day), /*#__PURE__*/React.createElement("div", {
      className: "month"
    }, event.month))), /*#__PURE__*/React.createElement("div", {
      className: "event-content"
    }, /*#__PURE__*/React.createElement("h3", null, /*#__PURE__*/React.createElement("a", {
      href: event.link,
      target: "_blank",
      title: "Visit Official Website"
    }, event.name)), /*#__PURE__*/React.createElement("p", null, event.descript), /*#__PURE__*/React.createElement("div", {
      className: "event-meta"
    }, /*#__PURE__*/React.createElement("span", null, /*#__PURE__*/React.createElement("svg", {
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: "currentColor",
      "stroke-width": "2"
    }, /*#__PURE__*/React.createElement("circle", {
      cx: "12",
      cy: "12",
      r: "10"
    }), /*#__PURE__*/React.createElement("polyline", {
      points: "12 6 12 12 16 14"
    })), event.time), /*#__PURE__*/React.createElement("span", null, /*#__PURE__*/React.createElement("svg", {
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: "currentColor",
      "stroke-width": "2"
    }, /*#__PURE__*/React.createElement("path", {
      d: "M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"
    }), /*#__PURE__*/React.createElement("circle", {
      cx: "12",
      cy: "10",
      r: "3"
    })), event.location))));
  }
}

// <!--- Component: Main --->
class Main extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      eventsData: [{
        id: 1,
        img: "images/SumidagawaAI.png",
        imgTitle: "Sumidagawa Hanabi Festival - AI-generated illustration",
        day: "25",
        month: "Jul",
        name: "Sumidagawa Hanabi Festival",
        link: "https://www.sumidagawa-hanabi.com",
        descript: "Sumidagawa Fireworks Festival is the oldest recorded fireworks display in Japan, dating back to 1733. It is a quintessential Tokyo summer tradition held to ward off evil spirits and entertain the masses.",
        time: "19:00 ~ 20:30",
        location: "隅田川, Tokyo, Japan"
      }, {
        id: 2,
        img: "images/NagaokaAI.png",
        imgTitle: "Nagaoka Hanabi Festival - AI-generated illustration",
        day: "02",
        month: "Aug",
        name: "Nagaoka Hanabi Festival",
        link: "https://nagaokamatsuri.com",
        descript: "First started in 1946 as a war-damage reconstruction event to mourn the deceased of WWII, the Nagaoka Fireworks Festival in Niigata Prefecture carries on the spirit of Japan through the decades.",
        time: "19:20 ~ 21:10",
        location: "信濃川の河川敷, Niigata, Japan"
      }, {
        id: 3,
        img: "images/SuwakoAI.png",
        imgTitle: "Suwako Hanabi Festival - AI-generated illustration",
        day: "15",
        month: "Aug",
        name: "Suwako Hanabi Festival",
        link: "https://suwako-hanabi.com",
        descript: "Known for launching one of the highest numbers of shells in Japan (over 40,000), this festival uses the natural mountain landscape surrounding Lake Suwa to create a thunderous acoustic experience.",
        time: "19:00 ~ 21:00",
        location: "諏訪湖, Nagano, Japan"
      }, {
        id: 4,
        img: "images/AkagawaAI.png",
        imgTitle: "Akagawa Hanabi Festival - AI-generated illustration",
        day: "15",
        month: "Aug",
        name: "Akagawa Hanabi Festival",
        link: "https://akagawahanabi.com",
        descript: "Consistently ranked as one of the most beautiful displays in Japan, Akagawa is famous for its 'wide-star-mine' sequences that span over 700 meters, synchronizing cutting-edge pyrotechnics with music.",
        time: "18:45 ~ 21:00",
        location: "赤川河畔, Yamagata, Japan"
      }, {
        id: 5,
        img: "images/OmagariAI.png",
        imgTitle: "Omagari Hanabi Festival - AI-generated illustration",
        day: "29",
        month: "Aug",
        name: "Omagari Hanabi Festival",
        link: "https://www.omagari-hanabi.com/",
        descript: "Witness breathtaking fireworks explode above accompanied by stories and music, which brings the show of light and sound together in a friendly festival setting at the end of August in the Daisen area.",
        time: "17:10 ~ 21:30",
        location: "大曲の花火公園, Akita, Japan"
      }, {
        id: 6,
        img: "images/TsuchiuraAI.png",
        imgTitle: "Tsuchiura Hanabi Festival - AI-generated illustration",
        day: "01",
        month: "Nov",
        name: "Tsuchiura Hanabi Competition",
        link: "https://www.tsuchiura-hanabi.jp",
        descript: "Tsuchiura All Japan Fireworks Competition is held every year in early November, to celebrate autumn harvest and thank farmers for their important work.",
        time: "17:30 ~ 20:00",
        location: "桜川畔, Ibaraki, Japan"
      }]
    };
  }
  render() {
    return /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement("div", {
      className: "grid-bg"
    }), /*#__PURE__*/React.createElement(Header, null), /*#__PURE__*/React.createElement("section", {
      className: "events",
      id: "events"
    }, /*#__PURE__*/React.createElement("div", {
      className: "section-header"
    }, /*#__PURE__*/React.createElement("h2", {
      className: "section-title"
    }, "Events"), /*#__PURE__*/React.createElement("p", {
      className: "section-subtitle"
    }, "Mark your calendar for these special festivals")), /*#__PURE__*/React.createElement("div", {
      className: "events-grid"
    }, this.state.eventsData.map(event => /*#__PURE__*/React.createElement(EventsCard, {
      key: event.id,
      event: event
    })))), /*#__PURE__*/React.createElement(Footer, null));
  }
}

// Render
function start() {
  ReactDOM.render(/*#__PURE__*/React.createElement(Main, null), document.getElementById('root'));
}
