// Component: <!-- Header -->
class Header extends React.Component{
    render(){
        return(
            <header>
                <div className="logo">
                    <div className="logo-icon">🎇</div>
                    <span className="logo-text">Hana<span>bi-3</span></span>
                </div>
            </header>
        );
    }
}

// Component: <!-- Footer -->
class Footer extends React.Component{
    render(){
        return(
            <footer>
                <div className="footer-content">
                    <p>@ All images on this website are generated by Gemini AI.</p>
                    <p>@ v3.0.0</p>
                </div>
            </footer>
        );
    }
}

// Component: <!-- Events Card Section -->
class EventsCard extends React.Component{
    render(){
        const { event } = this.props;
        return(
            <div className="event-card">
                <div className="event-image">
                    <img src={event.img} alt={event.name} title={event.imgTitle}/>
                    <div className="event-date-badge">
                        <div className="day">{event.day}</div>
                        <div className="month">{event.month}</div>
                    </div>
                </div>
                <div className="event-content">
                    <h3><a href ={event.link} target="_blank" title="Visit Official Website">{event.name}</a></h3>
                    <p>{event.descript}</p>
                    <div className="event-meta">
                        <span>
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <circle cx="12" cy="12" r="10"></circle>
                                <polyline points="12 6 12 12 16 14"></polyline>
                            </svg>
                            {event.time}
                        </span>
                        <span>
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path>
                                <circle cx="12" cy="10" r="3"></circle>
                            </svg>
                            {event.location}
                        </span>
                    </div>
                </div>
            </div>
        );
    }
}

// <!--- Component: Main --->
class Main extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            eventsData: [
                {
                    id: 1,
                    img: "images/NagaokaAI.png",
                    imgTitle: "Nagaoka Hanabi Festival - AI-generated illustration",
                    day: "02", month: "Aug",
                    name: "Nagaoka Hanabi Festival",
                    link: "https://nagaokamatsuri.com",
                    descript: "First started in 1946 as a war-damage reconstruction event to mourn the deceased of WWII, the Nagaoka Fireworks Festival in Niigata Prefecture carries on the spirit of Japan through the decades.",
                    time: "19:20 ~ 21:10", location: "信濃川の河川敷, Japan",
                    
                },
                {
                    id: 2,
                    img: "images/OmagariAI.png",
                    imgTitle: "Omagari Hanabi Festival - AI-generated illustration",
                    day: "29", month: "Aug",
                    name: "Omagari Hanabi Festival",
                    link: "https://www.omagari-hanabi.com/",
                    descript: "Witness breathtaking fireworks explode above accompanied by stories and music, which brings the show of light and sound together in a friendly festival setting at the end of August in the Daisen area.",
                    time: "17:10 ~ 21:30", location: "大曲の花火公園, Japan",
                },
                {
                    id: 3,
                    img: "images/TsuchiuraAI.png",
                    imgTitle: "Tsuchiura Hanabi Festival - AI-generated illustration",
                    day: "01", month: "Nov",
                    name: "Tsuchiura Hanabi Competition",
                    link: "https://www.tsuchiura-hanabi.jp",
                    descript: "Tsuchiura All Japan Fireworks Competition is held every year in early November, to celebrate autumn harvest and thank farmers for their important work.",
                    time: "17:30 ~ 20:00", location: "土浦市桜川畔, Japan",
                }
            ]
        };
    }

    render() {
        return (
            <React.Fragment>
                <div className="grid-bg"></div>
                <Header />
                <section className="events" id="events">
                    <div className="section-header">
                        <h2 className="section-title">Events</h2>
                        <p className="section-subtitle">Mark your calendar for these special festivals</p>
                    </div>
                    <div className="events-grid">
                        {this.state.eventsData.map(event => (
                            <EventsCard key={event.id} event={event} />
                        ))}
                    </div>
                </section>
                <Footer />
            </React.Fragment>
        );
    }
}

// Render
function start() {
    ReactDOM.render(<Main />, document.getElementById('root'));
}
